fix(kotlin-client): :bug: replace accept-encoding application/json to…
influxdata/influxdb-client-java pull request #205
Opened 2021-03-12 13:07 UTC by antoinedvd

## Proposed Changes

👋 Hi folks, I try make a humble contribution to fix a gzip compression issue during a query.

- the `Accept-Encoding` header is not used for influx 2.0 server because it always send back CSV data (the server didn't care if you asked for JSON)
- this header blocks the `Accept-Encoding: gzip` header from the `BridgeInterceptor` ([quick look here 👀](https://github.com/square/okhttp/blob/a8b5b5ecb24fa20cfd3b39fd81e7ba96c970d969/okhttp/src/main/kotlin/okhttp3/internal/http/BridgeInterceptor.kt#L69))

## Checklist

- [ ] CHANGELOG.md updated
- [ ] Rebased/mergeable
- [ ] A test has been added if appropriate
- [ ] `mvn test` completes successfully
- [ ] Commit messages are in [semantic format](https://seesparkbox.com/foundry/semantic_commit_messages)
- [ ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

2021-03-12 13:27 UTC, bednar requested changes
Thanks again for your PR 👍 

Please, could you also update following APIs:

- https://github.com/antoinedvd/influxdb-client-java/blob/5115baff7dd863b4119f5c40514ddba2db6e2e69/client/src/main/java/com/influxdb/client/internal/QueryApiImpl.java#L796
- https://github.com/antoinedvd/influxdb-client-java/blob/5115baff7dd863b4119f5c40514ddba2db6e2e69/client/src/main/java/com/influxdb/client/internal/QueryApiImpl.java#L814
- https://github.com/antoinedvd/influxdb-client-java/blob/5115baff7dd863b4119f5c40514ddba2db6e2e69/client-reactive/src/main/java/com/influxdb/client/reactive/internal/QueryReactiveApiImpl.java#L121
- https://github.com/antoinedvd/influxdb-client-java/blob/5115baff7dd863b4119f5c40514ddba2db6e2e69/client-reactive/src/main/java/com/influxdb/client/reactive/internal/QueryReactiveApiImpl.java#L259
- https://github.com/antoinedvd/influxdb-client-java/blob/5115baff7dd863b4119f5c40514ddba2db6e2e69/client-scala/src/main/scala/com/influxdb/client/scala/internal/QueryScalaApiImpl.scala#L105
- https://github.com/antoinedvd/influxdb-client-java/blob/5115baff7dd863b4119f5c40514ddba2db6e2e69/client-scala/src/main/scala/com/influxdb/client/scala/internal/QueryScalaApiImpl.scala#L280

?

2021-03-12 13:31 UTC, antoinedvd commented
> Thanks again for your PR +1
> 
> Please, could you also update following APIs:
> 
>     * https://github.com/antoinedvd/influxdb-client-java/blob/5115baff7dd863b4119f5c40514ddba2db6e2e69/client/src/main/java/com/influxdb/client/internal/QueryApiImpl.java#L796
> 
>     * https://github.com/antoinedvd/influxdb-client-java/blob/5115baff7dd863b4119f5c40514ddba2db6e2e69/client/src/main/java/com/influxdb/client/internal/QueryApiImpl.java#L814
> 
>     * https://github.com/antoinedvd/influxdb-client-java/blob/5115baff7dd863b4119f5c40514ddba2db6e2e69/client-reactive/src/main/java/com/influxdb/client/reactive/internal/QueryReactiveApiImpl.java#L121
> 
>     * https://github.com/antoinedvd/influxdb-client-java/blob/5115baff7dd863b4119f5c40514ddba2db6e2e69/client-reactive/src/main/java/com/influxdb/client/reactive/internal/QueryReactiveApiImpl.java#L259
> 
>     * https://github.com/antoinedvd/influxdb-client-java/blob/5115baff7dd863b4119f5c40514ddba2db6e2e69/client-scala/src/main/scala/com/influxdb/client/scala/internal/QueryScalaApiImpl.scala#L105
> 
>     * https://github.com/antoinedvd/influxdb-client-java/blob/5115baff7dd863b4119f5c40514ddba2db6e2e69/client-scala/src/main/scala/com/influxdb/client/scala/internal/QueryScalaApiImpl.scala#L280
> 
> 
> ?

Yes, I'll do that. 😉

2021-03-12 15:22 UTC, antoinedvd commented
@bednar it's done ✅

2021-03-15 06:53 UTC, bednar approved these changes
Thanks again for your PR 👍

2021-03-15 06:53 UTC, merged