Throwable not published as WriteErrorEvent #291
influxdata/influxdb-client-java pull request #292
Opened 2021-12-16 09:52 UTC by jsimomaa

Fixes #291

Closes #

## Proposed Changes

_Briefly describe your proposed changes:_

## Checklist

- [ ] CHANGELOG.md updated
- [ ] Rebased/mergeable
- [ ] A test has been added if appropriate
- [ ] `mvn test` completes successfully
- [ ] Commit messages are in [semantic format](https://seesparkbox.com/foundry/semantic_commit_messages)
- [ ] Sign [CLA](https://www.influxdata.com/legal/cla/) (if not already signed)

2022-01-11 07:37 UTC, bednar requested changes
Thanks for your PR 👍. 

There are a few requirements that must be be satisfy before we accept the PR:
1. Please fill description of your changes and satisfy `checklist`:
![image](https://user-images.githubusercontent.com/455137/148900372-03d31263-46f5-426e-a3c4-b03e32d0271d.png)
1. Please add a test that will cover your changes.

2022-01-18 12:18 UTC, bednar requested changes
Thanks again for your PR 👍. There are a few requirements that must be be satisfy before we accept the PR:

1. Please rebase your sources with master to fix conflicts in `CHANGELOG.md`.
2. Please update license header in `PublishRuntimeErrorAsWriteErrorEvent.java` by: `mvn license:format`

Regards.

2022-01-19 07:00 UTC, bednar requested changes
We're almost done. There's one last code style requirement:

2022-01-19 07:15 UTC, jsimomaa commented on client/src/test/java/com/influxdb/client/internal/PublishRuntimeErrorAsWriteErrorEvent.java
> +public class PublishRuntimeErrorAsWriteErrorEvent extends AbstractInfluxDBClientTest {
Thank you, I pushed this change

2022-01-19 07:32 UTC, bednar commented on client/src/test/java/com/influxdb/client/internal/PublishRuntimeErrorAsWriteErrorEvent.java
> +public class PublishRuntimeErrorAsWriteErrorEvent extends AbstractInfluxDBClientTest {
Thanks

2022-01-19 07:33 UTC, jsimomaa commented on client/src/test/java/com/influxdb/client/internal/PublishRuntimeErrorAsWriteErrorEvent.java
> +public class PublishRuntimeErrorAsWriteErrorEvent extends AbstractInfluxDBClientTest {
I noticed I forgot to save the refactor after the file rename and you had to rename the class yourself, thank you!

2022-01-19 07:39 UTC, bednar approved these changes

2022-01-19 07:39 UTC, merged