feat: update libraries, migrate to RxJava3
influxdata/influxdb-client-java pull request #298
Opened 2022-01-18 10:08 UTC by rhajek

Closes #

## Proposed Changes

_Briefly describe your proposed changes:_

## Checklist

- [ ] CHANGELOG.md updated
- [ ] Rebased/mergeable
- [ ] A test has been added if appropriate
- [ ] `mvn test` completes successfully
- [ ] Commit messages are in [semantic format](https://seesparkbox.com/foundry/semantic_commit_messages)
- [ ] Sign [CLA](https://www.influxdata.com/legal/cla/) (if not already signed)

2022-01-21 08:11 UTC, rhajek commented
There is a failing test:
com.influxdb.client.ITWriteTooManyData#backpressureAndBufferConsistency

It is probably related to RxJava3 `backpressure` and `groupBy` described in :
https://github.com/ReactiveX/RxJava/wiki/What's-different-in-3.0/080da79549b91abbd5af1c58cfe984e471454dcf#backpressure-in-groupby
* https://github.com/ReactiveX/RxJava/pull/6740
* https://github.com/ReactiveX/RxJava/issues/6641

The log contains following io.reactivex.rxjava3.exceptions.MissingBackpressureException stacktrace:

```
Jan 21, 2022 8:50:20 AM com.influxdb.client.write.events.WriteErrorEvent logEvent
SEVERE: The error occurred during writing of data
com.influxdb.exceptions.InfluxException: Unable to emit a new group (#2) due to lack of requests. Please make sure the downstream can always accept a new group as well as each group is consumed in order for the whole operator to be able to proceed.
	at com.influxdb.internal.AbstractRestClient.toInfluxException(AbstractRestClient.java:101)
	at com.influxdb.client.internal.AbstractWriteClient.lambda$new$12(AbstractWriteClient.java:184)
	at io.reactivex.rxjava3.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:79)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableDoFinally$DoFinallySubscriber.onError(FlowableDoFinally.java:89)
	at io.reactivex.rxjava3.internal.util.AtomicThrowable.tryTerminateConsumer(AtomicThrowable.java:94)
	at io.reactivex.rxjava3.internal.operators.mixed.FlowableConcatMapMaybe$ConcatMapMaybeSubscriber.drain(FlowableConcatMapMaybe.java:224)
	at io.reactivex.rxjava3.internal.operators.mixed.FlowableConcatMapMaybe$ConcatMapMaybeSubscriber.onError(FlowableConcatMapMaybe.java:146)
	at io.reactivex.rxjava3.internal.util.AtomicThrowable.tryTerminateConsumer(AtomicThrowable.java:94)
	at io.reactivex.rxjava3.internal.operators.mixed.FlowableConcatMapSingle$ConcatMapSingleSubscriber.drain(FlowableConcatMapSingle.java:219)
	at io.reactivex.rxjava3.internal.operators.mixed.FlowableConcatMapSingle$ConcatMapSingleSubscriber.onError(FlowableConcatMapSingle.java:146)
	at io.reactivex.rxjava3.internal.util.AtomicThrowable.tryTerminateConsumer(AtomicThrowable.java:94)
	at io.reactivex.rxjava3.internal.util.HalfSerializer.onError(HalfSerializer.java:67)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableConcatMap$ConcatMapImmediate.innerError(FlowableConcatMap.java:210)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableConcatMap$ConcatMapInner.onError(FlowableConcatMap.java:571)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableGroupBy$GroupBySubscriber.onError(FlowableGroupBy.java:220)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableGroupBy$GroupBySubscriber.onNext(FlowableGroupBy.java:197)
	at io.reactivex.rxjava3.processors.UnicastProcessor.drainRegular(UnicastProcessor.java:309)
	at io.reactivex.rxjava3.processors.UnicastProcessor.drain(UnicastProcessor.java:384)
	at io.reactivex.rxjava3.processors.UnicastProcessor.onNext(UnicastProcessor.java:444)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableWindowBoundary$WindowBoundaryMainSubscriber.drain(FlowableWindowBoundary.java:227)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableWindowBoundary$WindowBoundaryMainSubscriber.onNext(FlowableWindowBoundary.java:104)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowablePublishMulticast$MulticastProcessor.drain(FlowablePublishMulticast.java:404)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowablePublishMulticast$MulticastProcessor.onNext(FlowablePublishMulticast.java:221)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableOnBackpressureBufferStrategy$OnBackpressureBufferStrategySubscriber.drain(FlowableOnBackpressureBufferStrategy.java:234)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableOnBackpressureBufferStrategy$OnBackpressureBufferStrategySubscriber.onNext(FlowableOnBackpressureBufferStrategy.java:145)
	at io.reactivex.rxjava3.processors.PublishProcessor$PublishSubscription.onNext(PublishProcessor.java:363)
	at io.reactivex.rxjava3.processors.PublishProcessor.onNext(PublishProcessor.java:242)
	at io.reactivex.rxjava3.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:69)
	at io.reactivex.rxjava3.internal.subscriptions.ScalarSubscription.request(ScalarSubscription.java:55)
	at io.reactivex.rxjava3.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
	at io.reactivex.rxjava3.internal.subscribers.LambdaSubscriber.request(LambdaSubscriber.java:114)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableInternalHelper$RequestMax.accept(FlowableInternalHelper.java:216)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableInternalHelper$RequestMax.accept(FlowableInternalHelper.java:212)
	at io.reactivex.rxjava3.internal.subscribers.LambdaSubscriber.onSubscribe(LambdaSubscriber.java:52)
	at io.reactivex.rxjava3.internal.subscribers.BasicFuseableSubscriber.onSubscribe(BasicFuseableSubscriber.java:67)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableJust.subscribeActual(FlowableJust.java:34)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15747)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:38)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15747)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15683)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15644)
	at com.influxdb.client.internal.AbstractWriteClient.write(AbstractWriteClient.java:246)
	at com.influxdb.client.internal.AbstractWriteClient.lambda$write$14(AbstractWriteClient.java:225)
	at io.reactivex.rxjava3.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:69)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFilter$FilterSubscriber.tryOnNext(FlowableFilter.java:74)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromIterable$IteratorConditionalSubscription.fastPath(FlowableFromIterable.java:321)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromIterable$BaseRangeSubscription.request(FlowableFromIterable.java:129)
	at io.reactivex.rxjava3.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
	at io.reactivex.rxjava3.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
	at io.reactivex.rxjava3.internal.subscribers.LambdaSubscriber.request(LambdaSubscriber.java:114)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableInternalHelper$RequestMax.accept(FlowableInternalHelper.java:216)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableInternalHelper$RequestMax.accept(FlowableInternalHelper.java:212)
	at io.reactivex.rxjava3.internal.subscribers.LambdaSubscriber.onSubscribe(LambdaSubscriber.java:52)
	at io.reactivex.rxjava3.internal.subscribers.BasicFuseableSubscriber.onSubscribe(BasicFuseableSubscriber.java:67)
	at io.reactivex.rxjava3.internal.subscribers.BasicFuseableSubscriber.onSubscribe(BasicFuseableSubscriber.java:67)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromIterable.subscribe(FlowableFromIterable.java:66)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromIterable.subscribeActual(FlowableFromIterable.java:47)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15747)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFilter.subscribeActual(FlowableFilter.java:37)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15747)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:38)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15747)
	at io.reactivex.rxjava3.core.Flowable.subs [...]

2022-01-31 12:34 UTC, bednar commented
@rhajek tests are fixed

2022-01-31 12:38 UTC, bednar commented
@rhajek 

There are still libraries that need to be updated: `mvn versions:display-dependency-updates`

```bash
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] The InfluxDB 2.0 JVM Based Clients                                 [pom]
[INFO] The InfluxDB Client Utils                                          [jar]
[INFO] The InfluxDB Client Test Tools                                     [jar]
[INFO] The InfluxDB Client Core                                           [jar]
[INFO] The InfluxDB 1.7+ Flux Client                                      [jar]
[INFO] The Java InfluxDB 2.0 Client                                       [jar]
[INFO] The RxJava InfluxDB 2.0 Client                                     [jar]
[INFO] The Kotlin InfluxDB 2.0 Client                                     [jar]
[INFO] The Scala InfluxDB 2.0 Client [Scala 2.12]                         [jar]
[INFO] The Scala InfluxDB 2.0 Client [Scala 2.13]                         [jar]
[INFO] The OSGi InfluxDB 2.0 Client                                    [bundle]
[INFO] Apache Karaf Integration for InfluxDB 2.0                          [pom]
[INFO] Apache Karaf Features for InfluxDB 2.0                         [feature]
[INFO] Apache Karaf KAR for InfluxDB 2.0                                  [kar]
[INFO] Apache Karaf Assembly for InfluxDB 2.0                  [karaf-assembly]
[INFO] Spring Integration for InfluxDB 2.0                                [jar]
[INFO] The Flux DSL                                                       [jar]
[INFO] examples                                                           [jar]
[INFO] 
[INFO] --------------------< com.influxdb:influxdb-client >--------------------
[INFO] Building The InfluxDB 2.0 JVM Based Clients 4.2.0-SNAPSHOT        [1/18]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- versions-maven-plugin:2.7:display-dependency-updates (default-cli) @ influxdb-client ---
[INFO] The following dependencies in Dependency Management have newer versions:
[INFO]   com.squareup.okio:okio ............................... 2.10.0 -> 3.0.0
[INFO]   org.jetbrains.kotlinx:kotlinx-coroutines-core ...
[INFO]                                                 1.6.0 -> 1.6.0-native-mt
[INFO]   org.junit.jupiter:junit-jupiter-engine ................ 5.7.2 -> 5.8.2
[INFO]   org.junit.platform:junit-platform-runner .............. 1.7.2 -> 1.8.2
[INFO]   org.mockito:mockito-core ............................. 3.12.4 -> 4.3.1
[INFO]   org.mockito:mockito-junit-jupiter .................... 3.11.2 -> 4.3.1
[INFO] 
[INFO] 
[INFO] -----------------< com.influxdb:influxdb-client-utils >-----------------
[INFO] Building The InfluxDB Client Utils 4.2.0-SNAPSHOT                 [2/18]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- versions-maven-plugin:2.7:display-dependency-updates (default-cli) @ influxdb-client-utils ---
[INFO] The following dependencies in Dependency Management have newer versions:
[INFO]   com.squareup.okio:okio ............................... 2.10.0 -> 3.0.0
[INFO]   org.jetbrains.kotlinx:kotlinx-coroutines-core ...
[INFO]                                                 1.6.0 -> 1.6.0-native-mt
[INFO]   org.junit.jupiter:junit-jupiter-engine ................ 5.7.2 -> 5.8.2
[INFO]   org.junit.platform:junit-platform-runner .............. 1.7.2 -> 1.8.2
[INFO]   org.mockito:mockito-core ............................. 3.12.4 -> 4.3.1
[INFO]   org.mockito:mockito-junit-jupiter .................... 3.11.2 -> 4.3.1
[INFO] 
[INFO] 
[INFO] -----------------< com.influxdb:influxdb-client-test >------------------
[INFO] Building The InfluxDB Client Test Tools 4.2.0-SNAPSHOT            [3/18]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- versions-maven-plugin:2.7:display-dependency-updates (default-cli) @ influxdb-client-test ---
[INFO] The following dependencies in Dependency Management have newer versions:
[INFO]   com.squareup.okio:okio ............................... 2.10.0 -> 3.0.0
[INFO]   org.jetbrains.kotlinx:kotlinx-coroutines-core ...
[INFO]                                                 1.6.0 -> 1.6.0-native-mt
[INFO]   org.junit.jupiter:junit-jupiter-engine ................ 5.7.2 -> 5.8.2
[INFO]   org.junit.platform:junit-platform-runner .............. 1.7.2 -> 1.8.2
[INFO]   org.mockito:mockito-core ............................. 3.12.4 -> 4.3.1
[INFO]   org.mockito:mockito-junit-jupiter .................... 3.11.2 -> 4.3.1
[INFO] 
[INFO] 
[INFO] -----------------< com.influxdb:influxdb-client-core >------------------
[INFO] Building The InfluxDB Client Core 4.2.0-SNAPSHOT                  [4/18]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- versions-maven-plugin:2.7:display-dependency-updates (default-cli) @ influxdb-client-core ---
[INFO] The following dependencies in Dependency Management have newer versions:
[INFO]   com.squareup.okio:okio ............................... 2.10.0 -> 3.0.0
[INFO]   org.jetbrains.kotlinx:kotlinx-coroutines-core ...
[INFO]                                                 1.6.0 -> 1.6.0-native-mt
[INFO]   org.junit.jupiter:junit-jupiter-engine ................ 5.7.2 -> 5.8.2
[INFO]   org.junit.platform:junit-platform-runner .............. 1.7.2 -> 1.8.2
[INFO]   org.mockito:mockito-core ............................. 3.12.4 -> 4.3.1
[INFO]   org.mockito:mockito-junit-jupiter .................... 3.11.2 -> 4.3.1
[INFO] 
[INFO] 
[INFO] -----------------< com.influxdb:influxdb-client-flux >------------------
[INFO] Building The InfluxDB 1.7+ Flux Client 4.2.0-SNAPSHOT             [5/18]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- versions-maven-plugin:2.7:display-dependency-updates (default-cli) @ influxdb-client-flux ---
[INFO] The following dependencies in Dependency Management have newer versions:
[INFO]   com.squareup.okio:okio ............................... 2.10.0 -> 3.0.0
[INFO]   org.jetbrains.kotlinx:kotlinx-coroutines-core ...
[INFO]                                                 1.6.0 -> 1.6.0-native-mt
[INFO]   org.junit.jupiter:junit-jupiter-engine ................ 5.7.2 -> 5.8.2
[INFO]   org.junit.platform:junit-platform-runner .............. 1.7.2 -> 1.8.2
[INFO]   org.mockito:mockito-core ............................. 3.12.4 -> 4.3.1
[INFO]   org.mockito:mockito-junit-jupiter .................... 3.11.2 -> 4.3.1
[INFO] 
[INFO] 
[INFO] -----------------< com.influxdb:influxdb-client-java >------------------
[INFO] Building The Java InfluxDB 2.0 Client 4.2.0-SNAPSHOT              [6/18]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- versions-maven-plugin:2.7:display-dependency-updates (default-cli) @ influxdb-client-java ---
[INFO] The following dependencies in Dependency Management have newer versions:
[INFO]   com.squareup.okio:okio ............................... 2.10.0 -> 3.0.0
[INFO]   org.jetbrains.kotlinx:kotlinx-coroutines-core ...
[INFO]                                                 1.6.0 -> 1.6.0-native-mt
[INFO]   org.junit.jupiter:junit-jupiter-engine ................ 5.7.2 -> 5.8.2
[INFO]   org.junit.platform:junit-platform-runner .............. 1.7.2 -> 1.8.2
[INFO]   org.mockito:mockito-core ............................. 3.12.4 -> 4.3.1
[INFO]   org.mockito:mockito-junit-jupiter .................... 3.11.2 -> 4.3.1
[INFO] 
[INFO] 
[INFO] ---------------< com.influxdb:influxdb-client-reactive >----------------
[INFO] Building The RxJava InfluxDB 2.0 Client 4.2.0-SNAPSHOT            [7/18]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- versions-maven-plugin:2.7:display-dependency-updates (default-cli) @ influxdb-client-reactive ---
[INFO] The  [...]

2022-03-29 12:11 UTC, bednar requested changes
The upgrade to `rxjava3` is breaking change, please update the major version of the client and add notes about migration into CHANGELOG.md.

2022-04-05 05:31 UTC, bednar approved these changes
LGTM 👍

2022-04-05 07:10 UTC, merged