test: Add client performance/benchmark test
influxdata/influxdb-client-java pull request #312
Opened 2022-03-11 16:01 UTC by rhajek

## Proposed Changes

This PR adds client benchmarking test that validates the client writes in multithreaded load.

## Checklist

- [ ] CHANGELOG.md updated
- [ ] Rebased/mergeable
- [ ] A test has been added if appropriate
- [ ] `mvn test` completes successfully
- [ ] Commit messages are in [semantic format](https://seesparkbox.com/foundry/semantic_commit_messages)
- [ ] Sign [CLA](https://www.influxdata.com/legal/cla/) (if not already signed)

2022-03-14 13:51 UTC, bednar requested changes
Thanks for your PR 👍

There are a few requirements that must be be satisfy before we accept the PR:

2022-03-14 13:51 UTC, bednar commented on .circleci/config.yml
> +          influxdb-image: "quay.io/influxdb/influxdb:nightly"
Please use stable image:

```suggestion
```

2022-03-14 13:51 UTC, bednar commented on client/src/test/java/com/influxdb/client/ITBenchmarkTest.java
> +        bucket = bucketsApi.createBucket("benchmark-IT", findMyOrg());
The bucket name has to be unique:

```suggestion
        bucket = bucketsApi.createBucket(generateName("benchmark"), findMyOrg());
```

2022-03-14 13:51 UTC, bednar commented on client/src/test/java/com/influxdb/client/ITBenchmarkTest.java
> +
Delete organization is not necessary

```suggestion
```

2022-03-14 13:51 UTC, bednar commented on pom.xml
> +        <plugin.surefire.version>3.0.0-M3</plugin.surefire.version>
Please use latest milestone version:

```suggestion
        <plugin.surefire.version>3.0.0-M5</plugin.surefire.version>
```

2022-03-22 09:23 UTC, rhajek commented on client/src/test/java/com/influxdb/client/ITBenchmarkTest.java
> +
Delete of test organizations removed.

2022-03-22 09:51 UTC, bednar approved these changes
LGTM 👍

2022-03-22 13:01 UTC, merged