Could com.influxdb:influxdb-client-test:5.0.0-SNAPSHOT drop off redundant dependencies?
influxdata/influxdb-client-java pull request #320
Opened 2022-03-29 05:23 UTC by Celebrate-future

Hi! I found the pom file of project **_com.influxdb:influxdb-client-test:5.0.0-SNAPSHOT_** introduced **_26_** dependencies. However, among them, **_4_** libraries (**_15%_**) are not used by your project. I list the redundant dependencies below (labelled as red ones in the figure):
## Redundant dependencies
org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.3.70:compile
org.apiguardian:apiguardian-api:jar:1.1.0:compile
org.junit.platform:junit-platform-suite-api:jar:1.6.2:compile
org.jetbrains:annotations:jar:13.0:compile

---
Removing the redundant dependencies can reduce the size of project and prevent potential dependency conflict issues (i.e., multiple versions of the same library). More importantly, one of the redundant dependencies **_org.apiguardian:apiguardian-api:jar:1.1.0:compile_** induced dependency conflict in the dependency graph. As such, I suggest a refactoring operation for **_com.influxdb:influxdb-client-test:5.0.0-SNAPSHOT_**’s pom file.

The attached PR helps resolve the reported problem. It is safe to remove the unused libraries (we considered Java reflection relations when analyzing the dependencies). These changes have passed **_com.influxdb:influxdb-client-test:5.0.0-SNAPSHOT_**’s maven tests.

Best regards
![image](https://user-images.githubusercontent.com/78527112/160539057-d83df20d-0ba7-4926-b580-bb4a8c0966b1.png)

2022-03-29 05:46 UTC, bednar requested changes
Thanks for your PR 👍 
There are a few requirements that must be be satisfy before we accept the PR:

1. Can you please take a look at the falling checks?
![image](https://user-images.githubusercontent.com/455137/160541798-5392f0f2-79d7-403d-a9c5-78271620ddab.png)

1. Satisfy our checklist:
![image](https://user-images.githubusercontent.com/455137/160541704-1330c414-f723-40da-95b0-454e7bf18962.png)

2022-04-05 07:11 UTC, bednar commented
Hi @Celebrate-future,

Is this PR still relevant after https://github.com/influxdata/influxdb-client-java/pull/298?

Regards

2022-04-06 02:15 UTC, Celebrate-future commented
> Hi @Celebrate-future,
> 
> Is this PR still relevant after #298?
> 
> Regards

I think so.

2022-04-06 05:56 UTC, bednar commented
@Celebrate-future, can you please rebase sources with master and fix failed checks?

2022-04-08 02:44 UTC, Celebrate-future commented
> @Celebrate，您能否使用主数据库重新定位源并修复失败的检查？

Ok，I will finish it.

2022-07-17 15:40 UTC, bednar commented
This PR has been closed because it has not had recent activity. Please reopen if this PR is still important to you and you want to continue with them.

2022-07-17 15:40 UTC, closed without merging