feat: remove swagger-annotations dependency
influxdata/influxdb-client-java pull request #324
Opened 2022-04-05 12:57 UTC by rhajek

Closes #295 

This PR removes dependency on swagger annotations and adds new APIs:

* `ConfigService`
* `DebugService`
* `MetricsService`
* `RemoteConnectionsService`
* `ReplicationsService`

## Proposed Changes

_Briefly describe your proposed changes:_

## Checklist

- [ ] CHANGELOG.md updated
- [ ] Rebased/mergeable
- [ ] A test has been added if appropriate
- [ ] `mvn test` completes successfully
- [ ] Commit messages are in [semantic format](https://seesparkbox.com/foundry/semantic_commit_messages)
- [ ] Sign [CLA](https://www.influxdata.com/legal/cla/) (if not already signed)

2022-04-05 13:35 UTC, bednar requested changes

2022-04-05 13:35 UTC, bednar commented on CHANGELOG.md
> +- Add `MetricsService` to deal with exposed prometheus metrics
Please add also notes about: `DebugService` and `ReplicationService`.

2022-04-06 06:09 UTC, bednar requested changes

2022-04-06 06:09 UTC, bednar commented on client/src/main/java/com/influxdb/client/TelegrafsApi.java
> +    Telegraf createTelegraf(@Nonnull final TelegrafPluginRequest telegrafPluginRequest);
This is breaking change in our public API and should be notice in CHANGELOG.md.

2022-04-06 06:09 UTC, bednar commented on client/src/main/java/com/influxdb/client/TelegrafsApi.java
> +                            @Nonnull final TelegrafPluginRequest telegrafRequest);
This is breaking change in our public API and should be notice in CHANGELOG.md.

2022-04-06 06:09 UTC, bednar commented on client/src/main/java/com/influxdb/client/TelegrafsApi.java
> + *                 .type(TelegrafPlugin.TypeEnum.INPUT)
This is breaking change in our public API and should be notice in CHANGELOG.md.

2022-04-06 11:32 UTC, rhajek commented
CHANGELOG.md was updated.

2022-04-06 11:38 UTC, bednar approved these changes
LGTM 👍

2022-04-06 11:51 UTC, merged