feat: expose `/query` endpoint to use InfluxQL (#365)
influxdata/influxdb-client-java pull request #366
Opened 2022-06-23 13:12 UTC by Andy2003

Closes #365

## Proposed Changes

Added an endpoint to query against the InfluxQL endpoint (v1)

## Checklist

- [ ] CHANGELOG.md updated
- [x] Rebased/mergeable
- [x] A test has been added if appropriate
- [x] `mvn test` completes successfully
- [x] Commit messages are [conventional](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Sign [CLA](https://www.influxdata.com/legal/cla/) (if not already signed)

2022-06-24 05:22 UTC, bednar reviewed
@Andy2003 thanks for your fantastic PR 👍

Is it ready for review?

2022-06-24 09:38 UTC, Andy2003 commented
> Is it ready for review?

Yes it is

2022-07-12 16:36 UTC, Andy2003 commented
@bednar Is there anything I can do to get this merged?

2022-07-13 04:50 UTC, bednar commented
Hi @Andy2003,

sorry for the late. 

We currently discuss how to line up the support of other languages in the our client libraries. I hope so that we will be able to do a review soon and then merge it into `master`.

Regards

2022-07-29 06:20 UTC, bednar requested changes
Thanks again for your PR 👍  and sorry for the late. 

There are few requirements which has to be satisfied before we will merge this PR into master:

- Please add an example how to use the `InfluxQL` into `examples/src/main/java/example`, `examples/README.md`

and also satisfy following requirements:

2022-07-29 06:20 UTC, bednar commented on client-core/src/main/java/com/influxdb/query/InfluxQLQueryResult.java
> +    public static class Result {
Please add a javadoc documentation.

2022-07-29 06:20 UTC, bednar commented on client-core/src/main/java/com/influxdb/query/InfluxQLQueryResult.java
> +    public static class Series {
Please add a javadoc documentation.

2022-07-29 06:20 UTC, bednar commented on client-core/src/main/java/com/influxdb/query/InfluxQLQueryResult.java
> +        public class Record {
Please add a javadoc documentation.

2022-07-29 06:20 UTC, bednar commented on client-core/src/main/java/com/influxdb/query/InfluxQLQueryResult.java
> +public class InfluxQLQueryResult {
Make class final:

```suggestion
public final class InfluxQLQueryResult {
```

2022-07-29 06:20 UTC, bednar commented on client-core/src/main/java/com/influxdb/query/InfluxQLQueryResult.java
> +    public static class Result {
Make class final:

```suggestion
    public final static class Result {
```

2022-07-29 06:20 UTC, bednar commented on client-core/src/main/java/com/influxdb/query/InfluxQLQueryResult.java
> +    public static class Series {
Make class final:

```suggestion
    public final static class Series {
```

2022-07-29 06:20 UTC, bednar commented on client-core/src/main/java/com/influxdb/query/InfluxQLQueryResult.java
> +        public class Record {
Make class final:

```suggestion
        public final class Record {
```

2022-07-29 06:20 UTC, bednar commented on client/src/main/java/com/influxdb/client/InfluxQLQueryApi.java
> +    InfluxQLQueryResult query(@Nonnull final InfluxQLQuery influxQlQuery);
Please annotate the response with `@Nonnull`:

```suggestion
    @Nonnull
    InfluxQLQueryResult query(@Nonnull final InfluxQLQuery influxQlQuery);
```

2022-07-29 06:20 UTC, bednar commented on client/src/main/java/com/influxdb/client/InfluxQLQueryApi.java
> +    InfluxQLQueryResult query(
Please annotate the response with `@Nonnull`:

```suggestion
    @Nonnull
    InfluxQLQueryResult query(
```

2022-07-29 06:20 UTC, bednar commented on client/src/main/java/com/influxdb/client/InfluxQLQueryApi.java
> +     * @param valueExtractor a callback, to convert column values
Please add an example how to use the `valueExtractor` into this javadoc.

2022-07-29 06:20 UTC, bednar commented on client-core/src/main/java/com/influxdb/query/InfluxQLQueryResult.java
> +        public interface ValueExtractor {
Please add javadoc for this interface.

2022-07-29 06:20 UTC, bednar commented on client/src/main/java/com/influxdb/client/domain/InfluxQLQuery.java
> +    public InfluxQLQuery setRetentionPolicy(final String retentionPolicy) {
Please add `@Nullable` annotation:

```suggestion
    public InfluxQLQuery setRetentionPolicy(@Nullable final String retentionPolicy) {
```

2022-07-29 06:20 UTC, bednar commented on client/src/main/java/com/influxdb/client/domain/InfluxQLQuery.java
> +    public InfluxQLQuery setPrecision(final Precision precision) {
Please add `@Nullable` annotation:

```suggestion
    public InfluxQLQuery setPrecision(@Nullable final Precision precision) {
```

2022-07-29 06:20 UTC, bednar commented on client/src/main/java/com/influxdb/client/domain/InfluxQLQuery.java
> +    public enum Precision {
Please add javadoc to this `enum` and rename to `InfluxQLPrecision`:

```suggestion
    public enum InfluxQLPrecision {
```

2022-07-29 06:20 UTC, bednar commented on client/src/main/java/com/influxdb/client/domain/InfluxQLQuery.java
> +        public static Precision toTimePrecision(final TimeUnit t) {
Please add javadoc to this method and `@Nonnull` annotation:

```suggestion
        @Nonnull
        public static Precision toTimePrecision(@Nonnull final TimeUnit t) {
```

2022-07-29 10:05 UTC, bednar requested changes

2022-07-29 10:05 UTC, bednar commented on client-core/src/main/java/com/influxdb/query/InfluxQLQueryResult.java
> +            Object extractValue(String columnName, String rawValue, int resultIndex, String seriesName);
Please add `@Nullable` and `@Nonnull` annotations to method parameters and result.

2022-07-29 10:05 UTC, bednar commented on client/src/main/java/com/influxdb/client/internal/InfluxQLQueryApiImpl.java
> +    public InfluxQLQueryResult query(@NotNull final InfluxQLQuery influxQlQuery) {
Please use `@Nonnull`:

```suggestion
    public InfluxQLQueryResult query(@Nonnull final InfluxQLQuery influxQlQuery) {
```

2022-07-29 10:05 UTC, bednar commented on client/src/main/java/com/influxdb/client/internal/InfluxQLQueryApiImpl.java
> +            @NotNull final InfluxQLQuery influxQlQuery,
Please use `@Nonnull`:

```suggestion
            @Nonnull final InfluxQLQuery influxQlQuery,
```

2022-07-29 10:05 UTC, bednar commented on examples/src/main/java/example/InfluxQLExample.java
> +public class InfluxQLExample {
Please add link to this example into: `examples/README.md`

2022-08-02 05:18 UTC, bednar commented on CHANGELOG.md
> +1. [#366](https://github.com/influxdata/influxdb-client-java/pull/356): Added an endpoint to query with InfluxQL (v1) for more info see [README.md](./client).
Please rebase source and move this note into version 6.5.0

2022-08-02 06:09 UTC, bednar requested changes
@Andy2003 thanks again for your PR 👍 We are almost done..

2022-08-02 06:09 UTC, bednar commented on client/src/test/java/com/influxdb/client/ITInfluxQLQueryService.java
> +	}
Please add also a new test for `"SELECT * FROM \"influxql\""`.

2022-08-02 06:09 UTC, bednar commented on client/src/main/java/com/influxdb/client/internal/InfluxQLQueryApiImpl.java
> +        // int tagsCol = 1;
Please remove this line:

 ```suggestion
```

2022-08-02 06:09 UTC, bednar commented on client/src/main/java/com/influxdb/client/internal/InfluxQLQueryApiImpl.java
> +        int colsToSkip = 2;
Please add note why the index is `2`. It will be better for future maintenance.

2022-08-02 07:59 UTC, bednar approved these changes
LGTM 🚀 

@Andy2003 thanks you very much for this PR

2022-08-02 08:00 UTC, merged