feat: extend flux-dsl
influxdata/influxdb-client-java pull request #373
Opened 2022-07-05 09:22 UTC by Andy2003

## Proposed Changes

* Add ability to define imports for each flux function
* Add ability use multiple flux expressions
* Add ability to define custom functions
* Improve join flux, so it can be nested
* Add missing parameter variants for RangeFlux amd AggregateWindow
* Add TruncateTimeColumnFlux

## Checklist

- [ ] CHANGELOG.md updated
- [x] Rebased/mergeable
- [x] A test has been added if appropriate
- [x] `mvn test` completes successfully
- [x] Commit messages are [conventional](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Sign [CLA](https://www.influxdata.com/legal/cla/) (if not already signed)

2022-07-05 18:53 UTC, bednar requested changes
Hi @Andy2003, thanks for your PR 👍 

Can you satisfy following requirements: 
1. Add new functions into `flux-dsl/README.md`:
    - `InterpolateLinearFlux`
    - `TruncateTimeColumnFlux`
2. Add description how to use the `imports` into `flux-dsl/README.md`
3. Add description how to use the `AbstractFunctionFlux` into `flux-dsl/README.md`

and also:

2022-07-05 18:53 UTC, bednar commented on flux-dsl/src/main/java/com/influxdb/query/dsl/Flux.java
> +    public final RangeFlux range(final long start, final long stop) {
Please use `Long` object:

```suggestion
    public final RangeFlux range(final Long start, final Long stop) {
```

2022-07-05 18:53 UTC, bednar commented on flux-dsl/src/main/java/com/influxdb/query/dsl/Flux.java
> +    public final RangeFlux range(final long start) {
Please use `Long` object:

```suggestion
    public final RangeFlux range(final Long start) {
```

2022-07-05 18:53 UTC, bednar commented on flux-dsl/src/main/java/com/influxdb/query/dsl/HasImports.java
> +public interface HasImports {
Please add simple `javadoc` description.

2022-07-05 18:53 UTC, bednar commented on flux-dsl/src/main/java/com/influxdb/query/dsl/functions/RangeFlux.java
> +    public RangeFlux withStart(final long start) {
Please use `Long` object:

```suggestion
    public RangeFlux withStart(final Long start) {
```

2022-07-05 18:53 UTC, bednar commented on flux-dsl/src/main/java/com/influxdb/query/dsl/functions/RangeFlux.java
> +    public RangeFlux withStop(final long stop) {
Please use `Long` object:

```suggestion
    public RangeFlux withStop(final Long stop) {
```

2022-07-08 05:22 UTC, bednar approved these changes
LGMT 🚀 

Thanks again for your PR 👍. From my POV is ready to merge into `master`. Do you want to continue in work or it is done?

2022-07-08 06:47 UTC, Andy2003 commented
> Do you want to continue in work or it is done?

No it's all done, please merge!

2022-07-08 06:59 UTC, merged