influxdata#660 Pekko Streams support for scala client
influxdata/influxdb-client-java pull request #661
Opened 2023-12-15 15:12 UTC by utkuaydn

Support for Pekko Streams in the scala client

2024-01-08 09:20 UTC, bednar requested changes
Hi @utkuaydn,

I want to express my sincere gratitude for your pull request. It's a substantial improvement to our client, and we truly appreciate the effort and expertise you've brought into this project. Given Lightbend's decision to license future Akka releases under the Business Software License — which is incompatible with Open Source usage — I agree with your perspective that use Pekko streams. 

From our point of view the Akka Streams should be replaced by Pekko Streams.

Could you please update your pull request to reflect these changes? 

1. Remove Akka Streams: Completely transition away from Akka Streams and implement Pekko streams throughout the client.
1. Upgrade Major Version: Update the major version of the client to 7.0.0 to reflect this significant change and its potential impacts on compatibility.

These updates will align our client with a fully open-source framework and ensure its usability and compliance with open-source licensing moving forward.

Once again, thank you for your contribution, and we look forward to seeing the updated pull request.

2024-01-09 07:46 UTC, bednar requested changes
Thank you again for your PR! 👍 Before we can proceed with accepting it, there are a few requirements that need to be met:

1. Please rebase sources to fix conflict in `pom.xml`
2. Please satisfy our Checklist:
    ![image](https://github.com/influxdata/influxdb-client-java/assets/455137/ea9b987d-7efd-447e-b9d7-3de9ba478f2f)

and also:

2024-01-09 07:46 UTC, bednar commented on client-kotlin/README.md
> +  <version>7.0.0</version>
This should be actual stable version:
```suggestion
  <version>6.12.0</version>
```

2024-01-09 07:46 UTC, bednar commented on client-kotlin/README.md
> +    implementation "com.influxdb:influxdb-client-kotlin:7.0.0"
This should be actual stable version:
```suggestion
    implementation "com.influxdb:influxdb-client-kotlin:6.12.0"
```

2024-01-09 07:46 UTC, bednar commented on client-legacy/README.md
> +  <version>7.0.0</version>
This should be actual stable version:
```suggestion
  <version>6.12.0</version>
```

2024-01-09 07:46 UTC, bednar commented on client-legacy/README.md
> +    implementation "com.influxdb:influxdb-client-flux:7.0.0"
This should be actual stable version:
```suggestion
    implementation "com.influxdb:influxdb-client-flux:6.12.0"
```

2024-01-09 07:46 UTC, bednar commented on client-reactive/README.md
> +  <version>7.0.0</version>
This should be actual stable version:
```suggestion
  <version>6.12.0</version>
```

2024-01-09 07:46 UTC, bednar commented on client-reactive/README.md
> +    implementation "com.influxdb:influxdb-client-reactive:7.0.0"
This should be actual stable version:
```suggestion
    implementation "com.influxdb:influxdb-client-reactive:6.12.0"
```

2024-01-09 07:46 UTC, bednar commented on client-scala/README.md
> +  <version>7.0.0</version>
This should be actual stable version:
```suggestion
  <version>6.12.0</version>
```

2024-01-09 07:46 UTC, bednar commented on client-scala/README.md
> +    implementation "com.influxdb:influxdb-client-scala_2.12:7.0.0"
This should be actual stable version:
```suggestion
    implementation "com.influxdb:influxdb-client-scala_2.12:6.12.0"
```

2024-01-09 07:46 UTC, bednar commented on client-scala/README.md
> +  <version>7.0.0</version>
This should be actual stable version:
```suggestion
  <version>6.12.0</version>
```

2024-01-09 07:46 UTC, bednar commented on client-scala/README.md
> +    implementation "com.influxdb:influxdb-client-scala_2.13:7.0.0"
This should be actual stable version:
```suggestion
    implementation "com.influxdb:influxdb-client-scala_2.13:6.12.0"
```

2024-01-09 07:46 UTC, bednar commented on spring/README.md
> +  <version>7.0.0</version>
This should be actual stable version:
```suggestion
  <version>6.12.0</version>
```

2024-01-09 07:46 UTC, bednar commented on spring/README.md
> +    implementation "com.influxdb:influxdb-spring:7.0.0"
This should be actual stable version:
```suggestion
    implementation "com.influxdb:influxdb-spring:6.12.0"
```

2024-01-09 07:46 UTC, bednar commented on CHANGELOG.md
> +
Please add clarification for replacement of the Akka Streams, something like:
```suggestion

:warning: This client version discontinues support for Akka Streams and introduces support for Pekko Streams instead. Apache Pekko is a fork of [Akka](https://github.com/akka/akka) 2.6.x, created after the Akka project adopted the Business Source License, which is not compatible with open-source usage.

```

2024-01-09 19:10 UTC, utkuaydn commented
Hi @bednar,

I've completed the checklist and rebased the commit 👍

2024-01-10 07:15 UTC, bednar approved these changes
@utkuaydn thanks again for your PR 👍 

LGTM 🚀

2024-01-10 07:16 UTC, merged

2024-01-10 15:12 UTC, reyrobs commented
Well done Utku!